export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";
export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_CURRENT_CART = "CLEAR_CURRENT_CART";
